### PR TITLE
M63

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
@paweldomas @lyubomir I think this is now ready for review. I came up with a way to fix the transparent view bug on Android, please see the last commit and let me know what you think!

**Review by paweldomas — APPROVED** [review]
I've just tested that and it works great !

**Comment by paweldomas** [comment]
Hold on... I was testing from the wrong branch :(

**Comment by sboily** [comment]
Hello, i tried this branch, but it crash my app.

**Comment by paweldomas** [comment]
@sboily were you able to get any logs out of adb ?

**Comment by saghul** [comment]
@sboily also, indicating what Android and React Native versions you use is helpful.

**Comment by sboily** [comment]
Hello,

Logs is here: https://pastebin.com/be4DiPm2, but i'm not sure it can help, so let me know how i can help you with more details. I did many tests before sent my comment.
I'm using android 8.1 with a pixel 1 phone and my react-native version is 0.52.0. My application work great with react-native-webrtc 1.58.3. i haven't test on iOS for the moment.

Sylvain

**Comment by sboily** [comment]
I also tested with react native 0.49.3.

**Comment by saghul** [comment]
@sboily Your problem has nothing to do with this PR AFAIS. The problem seems to be that our fork is missing this commit from upstream: https://github.com/oney/react-native-webrtc/commit/dfdbd66075f5f7483a21432e5cbe2a39dacfb2a9

**Comment by sboily** [comment]
Oh you probably right, i spotted this issue, but at the begining i think it was my code and after i only played with the version. So, i will make another test!

**Comment by sboily** [comment]
ok it works with the good import :)

**Comment by saghul** [comment]
Thanks for confirming, I'm going to cherry-pick that one and rebase this on top.

**Pull request merged**
