### PR TITLE
updated webrtc build

### PR DESCRIPTION
**Pull request by globaljake**
updated webrtc build (12832) to fix issues on ARM64 devices

### CODE REVIEW

**Comment by lyubomir** [comment]
@globaljake, thank you very much for you contribution! How urgently do you need the WebRTC update merged? I'm in the middle of investigating a PeerConnection stats-related issue so I'm a bit reluctant to update WebRTC on my setup right now.

**Comment by globaljake** [comment]
Take your time all the time you need. I have something working on my side
so you are fine. Also thank YOU so much all the work you've put in on this!!

**Comment by lyubomir** [comment]
Hey, @globaljake! Could you please share how you built WebRTC? https://github.com/pristineio/webrtc-build-scripts? What does 12832 mean?

**Comment by globaljake** [comment]
@lyubomir sure yeah! I just followed the instructions for an iOS build from https://github.com/pristineio/webrtc-build-scripts and build the latest. 12832 means the build revision. I didn't specify build 12832 it was just the latest revision at the time.

Just for a heads up, it takes a while if you want to build it yourself. It took about an 1hr 45min for the me to do DEBUG build and about 45mins for the RELEASE build.

**Comment by lyubomir** [comment]
Upstream have updated the iOS & Android builds of WebRTC to the equivalent of Chromium 52 & I've just merged upstream's master into our lib-jitsi-meet branch. According to upstream, the iOS build is at revision 13039. Since that's newer than 12832, I'm closing this PR.

**Pull request closed without merging**
