### PR TITLE
M69 + 🤘

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by paweldomas** [comment]
LGTM just by looking at the code. Is it ready for testing ?

**Comment by saghul** [comment]
Yes, it’s ready for testing but it needs a rebase. I’ll do that tomorrow.

**Comment by saghul** [comment]
Also, I’ll extract some commits that apply to the current version to a separate PR, since we may want to be cautious with the update to M69.

**Comment by saghul** [comment]
@paweldomas Rebased and force-pushed. This now sits atop #34. Can you please review / land that first?

I want us to start testing M69 more actively after the next store releases are out, so we are not in a rush with this one.

Thanks!

**Pull request closed without merging**
